apiVersion: apps/v1
kind: Deployment
metadata:
  name: comentarios
  namespace: comentarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comentarios
  template:
    metadata:
      labels:
        app: comentarios
    spec:
      containers:
      - name: comentarios
        image: fsavila/desafio-app:1.0.5
        ports:
          - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
